### ISSUE TITLE
RabbitMQ support through the Bunny gem

### ISSUE THREAD

**Issue by bezelga** [hirefire/hirefire-resource#23]
I am looking forward to use Hirefire with RabbitMQ through the Bunny gem, I found [this ticket](http://support.hirefire.io/discussions/suggestions/60-rabbitmq-support) from Jan 2013 on Google but it seems that so far does not exist a Macro to easily integrate Bunny and Hirefire.

Is there any work done in this direction? If not I will give a shot to implement it and open a pull request.

**Comment by abezzub** [comment]
I need bunny support to run Sneakers workers (https://github.com/jondot/sneakers), I'll try to work on it.

**Comment by abezzub** [comment]
I created a PR: https://github.com/hirefire/hirefire-resource/pull/29

**Comment by meskyanichi** [comment]
Merged https://github.com/hirefire/hirefire-resource/pull/29
