### ISSUE TITLE
Staring with queue_classic 3.1, the `count` method returns scheduled jobs

### ISSUE THREAD

**Issue by jipiboily** [hirefire/hirefire-resource#24]
We added scheduled job support in queue_classic 3.1 and pushed a RC recently. I am in the process of getting our main app to use it and realized a few days ago that the `hirefire-resource` job will need to be changed to reflect this.

While easy to work around, right now, there is no official solution to this. Discussions is going to take place in https://github.com/QueueClassic/queue_classic/issues/246.

**Comment by morgoth** [comment]
The Que macro now uses the custom SQL https://github.com/hirefire/hirefire-resource/blob/master/lib/hirefire/macro/que.rb#L6-L9 so I guess this issue is not relevant any more
