### ISSUE TITLE
Delayed Job Queue Documentation

### ISSUE THREAD

**Issue by mikellevate** [hirefire/hirefire-resource#37]
I could be off base here, but I believe the documentation for setting specific queues with DelayedJob is incorrect. Currently, the code snippet is:
```
config.dyno(:dj_worker) do
    HireFire::Macro::Delayed::Job.queue(:encode, :compress)
  end
``` 

However, I was only able to get it to work by also passing `mapper: :active_record` as a parameter for queue.

**Comment by mrrooijen** [comment]
Correct! I've updated the README to correct this. Thanks!
