### ISSUE TITLE
Couldn't fetch job queues. An unknown error occurred. Contact support if this issue persists.

### ISSUE THREAD

**Issue by railslauncher** [hirefire/hirefire-resource#42]
Hi,

I am trying to setup HireFire for Sidekiq worker in Rails 4 app. But getting the below issue.

*Couldn't fetch job queues. An unknown error occurred. Contact support if this issue persists.*

```
Procfile:
web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
worker: bundle exec sidekiq

Gemfile:
gem 'hirefire-resource'

config/initializers/hirefire.rb
HireFire::Resource.configure do |config|
   config.dyno(:worker) do
      HireFire::Macro::Sidekiq.queue
   end
end
```

When I visit the info URL I get the below response.

`[{"name":"worker","quantity":1}]`

I have also configured the HIREFIRE_TOKEN.

Hirefire does not support Rails 4? Because the example is given for Rails 3

Thanks,
Soundar

**Comment by mrrooijen** [comment]
Responded via ticket/email.

**Comment by railslauncher** [comment]
:green_heart: HireFire
