### ISSUE TITLE
HireFire info call taking > 30 seconds and timing out

### ISSUE THREAD

**Issue by wrightling** [hirefire/hirefire-resource#63]
Hey folks - the #info call that HireFire makes to our rails app is taking over 30 seconds, and therefore timing out - basically 503 errors all around since a few days ago.

I updated to the latest version of this gem (0.10.1) to see if that would help, but no luck.

Here is our initializer for hirefire in our rails app:
```
HireFire::Resource.configure do |config|
  config.dyno(:integrations) do
    HireFire::Macro::Sidekiq.queue(:integrations)
  end

  config.dyno(:serial) do
    HireFire::Macro::Sidekiq.queue(:netsuite_high_priority)
    HireFire::Macro::Sidekiq.queue(:serial)
  end

  config.dyno(:serial2) do
    HireFire::Macro::Sidekiq.queue(:netsuite_high_priority)
    HireFire::Macro::Sidekiq.queue(:serial)
  end

  config.dyno(:worker) do
    HireFire::Macro::Sidekiq.queue(:salesforce)
    HireFire::Macro::Sidekiq.queue(:default)
    HireFire::Macro::Sidekiq.queue(:tank)
    HireFire::Macro::Sidekiq.queue(:mailers)
  end
end
```

FWIW here's a pic of the trace from New Relic for an example hirefire call:
![image](https://user-images.githubusercontent.com/1406395/210608727-88b0db95-67a2-4dfa-9403-d141fc565648.png)

![image](https://user-images.githubusercontent.com/1406395/210608801-07f7fb31-5048-4aa6-ba37-0f6519bd6501.png)

**Comment by mrrooijen** [comment]
Hey there,

Do you enqueue a large number of jobs to be processed at a later date?

For example:

```
MyWorker.perform_in(3.hours, "arg1, "arg2")
MyWorker.perform_at(3.hours.from_now, "arg1, "arg2")
```

**Comment by mrrooijen** [comment]
I just realized that your configuration has a problem.

Only the last value in the block is returned, so the following calls are ignored:

- HireFire::Macro::Sidekiq.queue(:netsuite_high_priority)
- HireFire::Macro::Sidekiq.queue(:salesforce)
- HireFire::Macro::Sidekiq.queue(:default)
- HireFire::Macro::Sidekiq.queue(:tank)

You can fix this by using the following configuration (it's also more efficient, so it should improve performance).

```rb
HireFire::Resource.configure do |config|
  config.dyno(:integrations) do
    HireFire::Macro::Sidekiq.queue(:integrations)
  end

  config.dyno(:serial) do
    HireFire::Macro::Sidekiq.queue(:netsuite_high_priority, :serial)
  end

  config.dyno(:serial2) do
    HireFire::Macro::Sidekiq.queue(:netsuite_high_priority, :serial)
  end

  config.dyno(:worker) do
    HireFire::Macro::Sidekiq.queue(:default, :mailers, :salesforce, :tank)
  end
end
```

If this doesn't improve performance enough, you can also tell HireFire to skip calculating scheduled jobs. Calculating scheduled jobs comes with a lot of overhead, which isn't an issue for smaller queues, but becomes an issue at larger scale. If you do have at least one Sidekiq process running at all times (i.e. at least one instance), then you can further improve performance by using the following configuration:

```rb
HireFire::Resource.configure do |config|
  config.dyno(:integrations) do
    HireFire::Macro::Sidekiq.queue(:integrations, skip_scheduled: true)
  end

  config.dyno(:serial) do
    HireFire::Macro::Sidekiq.queue(:netsuite_high_priority, :serial, skip_scheduled: true)
  end

  config.dyno(:serial2) do
    HireFire::Macro::Sidekiq.queue(:netsuite_high_priority, :serial, skip_scheduled: true)
  end

  config.dyno(:worker) do
    HireFire::Macro::Sidekiq.queue(:default, :mailers, :salesforce, :tank, skip_scheduled: true)
  end
end
```

Let me know if this improves the situation.

**Comment by wrightling** [comment]
Thank you - I will try the above and report back and close out the issue.

**Comment by wrightling** [comment]
Helped quite a bit - went ahead and used the "skip_scheduled: true" route and average response time dropped from around 30 seconds to about 12.5 seconds.
